name: dictionary
description: The ODW DICOM Data Dictionary Library
version: 0.5.1
authors:
  # original creator
  - Jim Philbin <jfphilbin@gmail.com>
  # subsequent contributors

homepage: https://github.com/OpenDICOMweb/dictionary.git

environment:
  sdk: ^1.21.0

dependencies:
  common:
  #  git:
  #    url: https://github.com/OpenDICOMweb/common.git
  #    ref: develop
  #    version: ^0.5.2
    path: C:/odw/sdk/common
    version: ^0.5.2

dev_dependencies:
  benchmark_harness: ^1.0.4
  grinder: ^0.8.0
  test: ^0.12.0

